A=set(input())
B=set(input())
print('caractere ce apar in ambele siruri',A.intersection(B))
print('caractere cel putin intr-un sir',A.union(B))
print('caractere ce apar in prima dar in a 2a nu ',A.difference(B))
